views.view.service_list:
  expected_config: { }
  update_actions:
    add:
      display:
        block_1:
          display_options:
            exposed_form:
              options:
                submit_button: Search
            filters:
              combine:
                id: combine
                table: views
                field: combine
                relationship: none
                group_type: group
                admin_label: ''
                plugin_id: combine
                operator: word
                value: ''
                group: 1
                exposed: true
                expose:
                  operator_id: combine_op
                  label: 'Advisory service name or search term'
                  description:
                  use_operator: false
                  operator: combine_op
                  operator_limit_selection: false
                  operator_list: { }
                  identifier: combine
                  required: false
                  remember: false
                  multiple: false
                  remember_roles:
                    authenticated: authenticated
                    anonymous: '0'
                    read_only: '0'
                    content_producer: '0'
                    editor: '0'
                    admin: '0'
                  placeholder: 'e.g. Social Counseling, Health, or Digital Search'
                is_grouped: false
                group_info:
                  label: ''
                  description: ''
                  identifier: ''
                  optional: true
                  widget: select
                  multiple: false
                  remember: false
                  default_group: All
                  default_group_multiple: { }
                  group_items: { }
                fields:
                  name: name
                  name_synonyms: name_synonyms
                  description__summary: description__summary
